export var menuCategories = [
    {
        name: "all items",
        lableFarsi: "همه موارد"
    },
    {
        name: "starters",
        lableFarsi: "پیش غذا"
    },
    {
        name: "main dishes",
        lableFarsi: "غذای اصلی"
    },
    {
        name: "desserts",
        lableFarsi: "دسر"
    },
    {
        name: "hot drinks",
        lableFarsi: "نوشیدنی گرم"
    },
    {
        name: "cold drinks",
        lableFarsi: "نوشیدنی سرد"
    },
];
export var menuItems = [
    {
        id: 1,
        name: "آیس آمریکانو",
        description: "۲۹۰ میلی لیتر، ۲ شات اسپرسو، قهوه ۱۰۰% عربیکا، یخ، ظرف شیشه ای",
        price: 79000,
        photo: "./images/items/item001.jpeg",
        isNew: false,
        category: "نوشیدنی سرد",
    },
    {
        id: 2,
        name: "آیس لته",
        description: "۲۶۰ میلی لیتر، شیر، ۲ شات اسپرسو قهوه ۱۰۰% عربیکا، یخ، ظرف شیشه ای",
        price: 85000,
        photo: "./images/items/item002.jpeg",
        isNew: false,
        category: "نوشیدنی سرد",
    },
    {
        id: 3,
        name: "آیس موکا",
        description: "۲۶۰ میلی لیتر، شیر، ۲ شات اسپرسو قهوه ۱۰۰% عربیکا، یخ، شکلات، ظرف شیشه ای",
        price: 97000,
        photo: "./images/items/item003.jpeg",
        isNew: false,
        category: "نوشیدنی سرد",
    },
    {
        id: 4,
        name: "منگو پشن فروت تی",
        description: "طعم دهنده طبیعی انبه و پشن فروت، چای سیاه، یخ",
        price: 90000,
        photo: "./images/items/item004.jpeg",
        isNew: false,
        category: "نوشیدنی سرد",
    },
    {
        id: 5,
        name: "سالاد بیف",
        description: "فیله گوساله، کاهو بنفش، سس مخصوص",
        price: 340000,
        photo: "./images/items/item005.jpeg",
        isNew: false,
        category: "پیش غذا",
    },
    {
        id: 6,
        name: "سالاد مرغ و قارچ",
        description: "فیله مرغ گریل شده، ماست، خامه، سس مایونز",
        price: 266000,
        photo: "./images/items/item006.jpeg",
        isNew: false,
        category: "پیش غذا",
    },
    {
        id: 7,
        name: "سالاد دریایی",
        description: "ماهی سالمون آب پز، میگو آب پز، میکس کرپ اسموکی",
        price: 360000,
        photo: "./images/items/item007.jpeg",
        isNew: false,
        category: "پیش غذا",
    },
    {
        id: 8,
        name: "سالاد سبز",
        description: "کاهو بنفش، سس سبز مخصوص",
        price: 210000,
        photo: "./images/items/item008.jpeg",
        isNew: false,
        category: "پیش غذا",
    },
    {
        id: 9,
        name: "اسپرینگ رول سبزیجات",
        description: "۵ عدد، سس چیلی تای",
        price: 240000,
        photo: "./images/items/item009.jpeg",
        isNew: false,
        category: "پیش غذا",
    },
    {
        id: 10,
        name: "آب سیب",
        description: "آب سیب طبیعی",
        price: 80000,
        photo: "./images/items/item010.jpg",
        isNew: false,
        category: "نوشیدنی سرد",
    },
    {
        id: 11,
        name: "موهیتو",
        description: "",
        price: 95000,
        photo: "./images/items/item011.jpg",
        isNew: false,
        category: "نوشیدنی سرد",
    },
    {
        id: 12,
        name: "سینی میوه",
        description: "هندوانه، طالبی، توت فرنگی، گوجه سبز، سیب، آناناس",
        price: 299000,
        photo: "./images/items/item012.jpeg",
        isNew: false,
        category: "دسر",
    },
    {
        id: 13,
        name: "بستنی رویال",
        description: "۲ اسکوپ بستنی وانیل، ۲ اسکوپ بستنی شکلات، شوکو رول، اوریو",
        price: 140000,
        photo: "./images/items/item013.jpg",
        isNew: false,
        category: "دسر",
    },
    {
        id: 14,
        name: "چیز کیک پنیری",
        description: "",
        price: 128000,
        photo: "./images/items/item014.jpeg",
        isNew: false,
        category: "دسر",
    },
    {
        id: 15,
        name: "حمص ناتور",
        description: "۲۰۰ گرم حمص، ارده، نخود، روغن زیتون، نان گرد",
        price: 144000,
        photo: "./images/items/item015.jpeg",
        isNew: false,
        category: "پیش غذا",
    },
    {
        id: 16,
        name: "سوپ قارچ",
        description: "یک نفره، قارچ، دارچین، بشامل، ذرت، شیر، خامه",
        price: 138000,
        photo: "./images/items/item016.jpeg",
        isNew: false,
        category: "پیش غذا",
    },
    {
        id: 17,
        name: "نان سیر",
        description: "۱۲۰ گرم خمیر پیتزا، سیر، ادویه پنیر پیتزا",
        price: 178000,
        photo: "./images/items/item017.jpeg",
        isNew: false,
        category: "پیش غذا",
    },
    {
        id: 18,
        name: "سالاد سزار",
        description: "یک نفره، کاهو، سس سزار، پنیر پارمسان وگن، پروتیین سوخاری گیاهی، نان سیر",
        price: 198000,
        photo: "./images/items/item018.jpeg",
        isNew: false,
        category: "پیش غذا",
    },
    {
        id: 19,
        name: "سالاد مخلوط فرانسوی",
        description: "یک نفره، ۱۰۰ گرم مخلوط سبزیجات (کاهو پیچ، کاهو فرانسوی)، ۲۰ گرم سیب و پرتقال، ۴۰ گرم مخلوط لوبیا (لوبیا سفید، لوبیا عروس)، ۲ عدد مغز گردو، کنجد، مخلوط سه تخمه، ۸۰ گرم سس توت فرنگی",
        price: 228000,
        photo: "./images/items/item019.jpeg",
        isNew: false,
        category: "پیش غذا",
    },
    {
        id: 20,
        name: "سالاد کینوا",
        description: "یک نفره، کینوا، فلفل قرمز، پیاز، انار، زیتون سبز، گوجه فرنگی، سس مخصوص",
        price: 238000,
        photo: "./images/items/item020.jpeg",
        isNew: false,
        category: "پیش غذا",
    },
    {
        id: 21,
        name: "کافه لاته",
        description: "ترکیب اسپرسو دو شات و شیر با فوم کم، ۳۶۰ میلی‌ لیتر",
        price: 84800,
        photo: "./images/items/item021.jpeg",
        isNew: false,
        category: "نوشیدنی گرم",
    },
    {
        id: 22,
        name: "آمریکانو متوسط",
        description: "ترکیب اسپرسو دو شات و آب جوش، ۳۶۰ میلی‌ لیتر",
        price: 64800,
        photo: "./images/items/item022.jpeg",
        isNew: false,
        category: "نوشیدنی گرم",
    },
    {
        id: 23,
        name: "کپوچینو",
        description: "ترکیب اسپرسو دو شات و شیر با فوم زیاد، ۳۶۰ میلی‌ لیتر",
        price: 84800,
        photo: "./images/items/item023.jpeg",
        isNew: false,
        category: "نوشیدنی گرم",
    },
    {
        id: 24,
        name: "قهوه دمی",
        description: "قهوه تک خاستگاه عربیکا، دم آوری با فیلتر کاغذی، ۳۶۰ میلی‌ لیتر",
        price: 64800,
        photo: "./images/items/item024.jpeg",
        isNew: false,
        category: "نوشیدنی گرم",
    },
    {
        id: 25,
        name: "کورتادو",
        description: "ترکیب اسپرسو دو شات و شیر با فوم کم، ۱۸۰ میلی‌ لیتر",
        price: 77800,
        photo: "./images/items/item025.jpeg",
        isNew: false,
        category: "نوشیدنی گرم",
    },
    {
        id: 26,
        name: "کافه موکا",
        description: "ترکیب اسپرسو دو شات، شکلات مخصوص لمیز و شیر با فوم کم، ۳۶۰ میلی‌ لیتر",
        price: 95800,
        photo: "./images/items/item026.jpeg",
        isNew: false,
        category: "نوشیدنی گرم",
    },
    {
        id: 27,
        name: "کارامل ماکیاتو",
        description: "ترکیب اسپرسو دو شات، طعم دهنده وانیل، سس کارامل و شیر با فوم نسبتا زیاد، ۳۶۰ میلی لیتر",
        price: 95800,
        photo: "./images/items/item027.jpeg",
        isNew: false,
        category: "نوشیدنی گرم",
    },
    {
        id: 28,
        name: "براونی",
        description: "کیک اسفنجی شکلاتی، تاپینگ بریلو کارامل و پودر کاکایو، ۶۰ گرم",
        price: 94800,
        photo: "./images/items/item028.jpeg",
        isNew: false,
        category: "دسر",
    },
    {
        id: 29,
        name: "کراسان ساده",
        description: "خمیر هزار لایه، کره نیوزلندی، ۹۰ گرم",
        price: 52800,
        photo: "./images/items/item029.jpeg",
        isNew: false,
        category: "دسر",
    },
    {
        id: 30,
        name: "تارت شکلات فندق",
        description: "نان تارت شکلاتی با مغز شکلات تلخ، سس کارامل نمکی، موس شکلات، تاپینگ پرالین فندق، ۱۲۵ گرم",
        price: 94800,
        photo: "./images/items/item030.jpeg",
        isNew: false,
        category: "دسر",
    },
    {
        id: 31,
        name: "بشقاب شنیسل مرغ",
        description: "۲۰۰ گرم سینه مرغ گریل شده، یک عدد تخم مرغ نیمرو، ۱۰۰ گرم سس قارچ",
        price: 300000,
        photo: "./images/items/item031.jpeg",
        isNew: false,
        category: "غذای اصلی",
    },
    {
        id: 32,
        name: "بشقاب سبزیجات",
        description: "۱۸۰ گرم پوره سیب زمینی، ۵۰ گرم بادمجان، ۵۰ گرم کدو، فلفل دلمه ای، ۵۰ گرم قارچ، کلم",
        price: 250000,
        photo: "./images/items/item032.jpeg",
        isNew: false,
        category: "غذای اصلی",
    },
    {
        id: 33,
        name: "پاستا آلفردو",
        description: "پاستا یک نفره، ۲۰۰ گرم پنه، ۱۲۰ گرم فیله مرغ گریل شده، قارچ، سس مخصوص",
        price: 250000,
        photo: "./images/items/item033.jpeg",
        isNew: false,
        category: "غذای اصلی",
    },
    {
        id: 34,
        name: "پاستا پستو",
        description: "پاستا یک نفره، ۲۰۰ گرم پنه، ۱۲۰ گرم فیله مرغ گریل شده، قارچ، سس پستو، حریره سیر",
        price: 240000,
        photo: "./images/items/item034.jpeg",
        isNew: false,
        category: "غذای اصلی",
    },
    {
        id: 35,
        name: "پاستا بلونز",
        description: "پاستا یک نفره، ۲۰۰ گرم اسپاگتی، ۱۰۰ گرم گوشت گوساله چرخ شده، پیاز، فلفل دلمه ای، هویج، قارچ، گوجه فرنگی",
        price: 260000,
        photo: "./images/items/item031.jpeg",
        isNew: false,
        category: "غذای اصلی",
    },
    {
        id: 36,
        name: "فیله استیک",
        description: "۲۰۰ گرم گوشت فیله گوساله، دورچین: ۱۰۰ گرم پوره سیب زمینی، بادمجان، کلم بروکلی، کدو، قارچ، سس قارچ",
        price: 650000,
        photo: "./images/items/item036.jpeg",
        isNew: false,
        category: "غذای اصلی",
    },
    {
        id: 37,
        name: "استیک مرغ با سس پرتقال",
        description: "۲۵۰ گرم فیله مرغ، دورچین: ۱۰۰ گرم پوره سیب زمینی، بادمجان، کلم بروکلی، کدو، قارچ، سس پرتقال",
        price: 320000,
        photo: "./images/items/item037.jpeg",
        isNew: false,
        category: "غذای اصلی",
    },
    {
        id: 38,
        name: "ساندویچ چاباتا زبان",
        description: "۱۰۰ گرم زبان گوساله تکه ای، سس خامه، قارچ، نان چاباتا",
        price: 260000,
        photo: "./images/items/item038.jpeg",
        isNew: false,
        category: "غذای اصلی",
    },
    {
        id: 39,
        name: "ساندویچ چاباتا مرغ کاری",
        description: "۲۰۰ گرم فیله مرغ تکه ای، کاهو فرانسوی، گوجه فرنگی، سس کاری، نان چاباتا",
        price: 220000,
        photo: "./images/items/item039.jpeg",
        isNew: false,
        category: "غذای اصلی",
    },
    // {
    //     id: 40,
    //     name: "ساندویچ چاباتا پستو موزارلا",
    //     description: "۵ گرم ریحان، ۶۰ گرم گوجه فرنگی، ۵۰ گرم سس پستو، پنیر موزارلا، نان چاباتا",
    //     price: 200000,
    //     photo: "./images/items/item040.jpeg",
    //     isNew: false,
    //     category: "غذای اصلی",
    // },
];